trigger:
  branches:
    include:
      - pipeline
pr: none

variables:
  skipNugetSecurityAnalysis: true
  skipComponentGovernanceDetection: true

resources:
  repositories:
    - repository: docs
      type: github
      endpoint: Monaco
      name: microsoft/vscode-docs
      ref: pipeline
    - repository: website
      type: github
      endpoint: Monaco
      name: microsoft/vscode-website
      ref: main

stages:
- stage: testCheckout
  jobs:
    - job: testCheckout
      pool:
        vmImage: windows-latest
      steps:
        - checkout: website
          clean: true
          path: vscode-website
          persistCredentials: true
          fetchDepth: 1
        - checkout: docs
          clean: true
          path: vscode-website/vscode-docs
          persistCredentials: true
          fetchDepth: 1
          lfs: true
        - task: NodeTool@0
          displayName: Use Node 12.18.0
          inputs:
            versionSpec: 12.18.0
            checkLatest: true